### ISSUE TITLE
Possible to detect language?

### ISSUE THREAD

**Issue by unknownguy2002** [franciscop/translate#1]
Yandex Translate can detect the language of input, is it possible to utilise this using this module?

**Comment by franciscop** [comment]
I think both of the current engines support auto-detecting the text language, not forcing it to be English. Do you mean that? Or do you mean to put a string and return `en` or similar? The former could be added to `translate`, unfortunately the latter would be out of scope, please check [other packages for language detection](https://www.npmjs.com/package/languagedetect).

**Comment by unknownguy2002** [comment]
Yes, I meant the former.

**Comment by unknownguy2002** [comment]
According to the docs, `from: the string of the language to translate to. It can be in any of the two ISO 639 (1 or 2) or the full name in English like Spanish. Also defaults to en.`

**Comment by unknownguy2002** [comment]
There is no auto-detection option

**Comment by franciscop** [comment]
So, while I agree this is useful, I don't have the need to do this and the priority of this in very low. I would accept/review a PR adding this functionality, but as it stands right now I'm not going to implement it.
