### ISSUE TITLE
How to return translated word instead of console log?

### ISSUE THREAD

**Issue by joge17** [franciscop/translate#12]
I am trying to return the translated word from the function translateWord. When I do `console.log(val)` inside of `then()` I get the correct translated word. But when I do `return val;` I get `undefined`.

This logs the translated word to the console:

```
translateWord(word) {
    let promise = translate(word, 'es');
    promise.then((val) => {
      console.log(val);
    })
}
```

This returns `undefined`: 

```
  translateWord(word) {
    let promise = translate(word, 'es');
    promise.then((val) => {
      return val;
    })
}
```

How can I return the translated word from the `translateWord` function?

**Comment by franciscop** [comment]
Since it is an asynchronous operation, you cannot return the plain value. With promises you'd have to use `await`. Please read this amazing article:

- https://ponyfoo.com/articles/understanding-javascript-async-await
