### ISSUE TITLE
Add format=text to google translate query

### ISSUE THREAD

**Issue by MichalRemis** [franciscop/translate#13]
Firstly, thank you for nice library. Currently when translating longer text with new lines, translation via Google removes new lines and merges text into one line. This could be fixed by adding format="text" query parameter too translation query. Or you could make this optional as translate option format = 'html'/'text'

https://cloud.google.com/translate/docs/reference/translate

**Comment by franciscop** [comment]
Oh interesting, I was thinking back then about allowing arrays like `translate(['hello', 'world'], ...)` for multi-string translation but this seems to kill two birds with one shot.

Please feel free to make a PR (the code is minimal, look into "engines.js"), but I won't be able to bump it on npm until next week

**Comment by franciscop** [comment]
👍  published as 1.1.0, thanks for the PR!
