### ISSUE TITLE
convert to 'hebrew' not work

### ISSUE THREAD

**Issue by Krunalvaghasiya** [franciscop/translate#15]
Error code:

`translate.min.js:1 Uncaught (in promise) Error: The name "iw" is not part of the ISO 639-1 and we couldn't automatically parse it :(
    at language (translate.min.js:1)
    at translate (translate.min.js:1)`

**Comment by franciscop** [comment]
Hebrew code seems to be `"he"`, it was officially changed in 1989 [according to Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Please feel free to reopen if this is an issue otherwise.
