### ISSUE TITLE
Doesn't work on Ionic 4 :(

### ISSUE THREAD

**Issue by manel00** [franciscop/translate#16]
I'm trying to make it works there but it doesn't, can you make a little tutorial (readme minimum) to explain what should i do to make it works on Ionic 4? Thank you so much

Regards

**Comment by franciscop** [comment]
Could you share some code of how you are trying to make it work and what doesn't work? How do you know it's not working? What error message do you see?

**Comment by manel00** [comment]
`[ng] WARNING in ./node_modules/encoding/lib/iconv-loader.js 9:12-34
[ng] Critical dependency: the request of a dependency is an expression
[ng] 
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/index.js
[ng] Module not found: Error: Can't resolve 'http' in '........./node_modules/translate/node_modules/node-fetch'
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/lib/response.js
[ng] Module not found: Error: Can't resolve 'http' in '........./node_modules/translate/node_modules/node-fetch/lib'
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/index.js
[ng] Module not found: Error: Can't resolve 'https' in '........./node_modules/translate/node_modules/node-fetch'
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/index.js
[ng] Module not found: Error: Can't resolve 'stream' in '........./node_modules/translate/node_modules/node-fetch'
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/lib/body.js
[ng] Module not found: Error: Can't resolve 'stream' in '........./node_modules/translate/node_modules/node-fetch/lib'
[ng] ERROR in ./node_modules/translate/node_modules/node-fetch/index.js
[ng] Module not found: Error: Can't resolve 'zlib' in '........./node_modules/translate/node_modules/node-fetch'
[ng] ℹ ｢wdm｣: Failed to compile.`

That's the error **when i do ionic serve**...

**Comment by rosostolato** [comment]
I guess that it has something to do with `node-fetch` package... I forked this project to remove it and then it worked on  my angular project. Take a look at my [commit](https://github.com/rosostolato/translate/commit/34ab153e6678da8d542c6b59257f8dcfe59352ac).

**Comment by franciscop** [comment]
So I've been trying to fix this for a while. From the looks of this issue, it would seem like Ionic is running this code first in an environment without `fetch()`, and _then_ it's trying to load that code into the browser. So it is polyfilled first, but then the polyfill doesn't work in the browser.

If this is correct, I added a try/catch on the just-released `1.1.2` version that will hopefully fix this, but I'm highly unfamiliar with Ionic so please let me know if that doesn't work.
