### ISSUE TITLE
Feature request: Typescript types

### ISSUE THREAD

**Issue by euberdeveloper** [franciscop/translate#19]
Hi!

Your module is very useful

I am currently using typescript, usually they are published with the package, in the "type" property of the package.json. 
I see that there is not any, so I tried with "npm i -D @types/translate" but there is no such module.

Are you planning to add this feature?

**Comment by franciscop** [comment]
No, I don't like typescript. I believe anyone can contribute to `@types/translate` though, so it might be a good idea to contribute there, the API of this library is unlikely to change as I consider it "done" (except for bug fixes).
