### ISSUE TITLE
Slowdown: 20 per 1 minute

### ISSUE THREAD

**Issue by mgobishop** [franciscop/translate#21]
Help! I'm using the Libre engine but it's preventing me from making many requests. It throws an error - 'Slowdown: 20 per 1 minute'. I've looked at the Libre docs and they suggest setting the --req-limit option or starting Libre with the --api-keys option and issuing a new key. I'm using your wrapper which neatly hides all of that - not sure how I can get the API key... so how can I increase this limit using your package with Libre? Thanks.

**Comment by mgobishop** [comment]
I've made a pull request! Hopefully I've done it ok? So... how do I get an API-Key???

**Comment by franciscop** [comment]
Hi @mgobishop , it was published as `translate@1.2.2`! Please give it a try.

To use the API Key, it's used like other engines [documented in the Engines section](https://github.com/franciscop/translate#engines):

```js
// ... include translate

translate.engine = "libre";
translate.key = "YOUR-KEY-HERE";

// ... use translate()
```

How to get the key? In the homepage of Libretranslate, it says:

> The public API on libretranslate.com should be used for testing, personal or infrequent use. If you're going to run an application in production, please [host your own server](https://github.com/uav4geo/LibreTranslate) or [get in touch](https://uav4geo.com/contact) to obtain an API key.

**Comment by FranciscoMendes10866** [comment]
Hello malta!

I am also using the Liber Engine and decided to spin up a LibreTranslate container and through the terminal I created an api key.

However my question is as follows:
`How can I use Libre Translate that is in my docker container?`

Have a great day!

**Comment by FranciscoMendes10866** [comment]
Hello guys!

I am also using the Liber Engine and decided to spin up a LibreTranslate container and through the terminal I created an API key.

However, my question is how can I use the Libre engine that I have in the local docker container?

Have a great day!

**Comment by franciscop** [comment]
Okay thanks for waiting, I just published a new release, `translate@1.2.3`! Now with Libretranslate there are two ways of running it 🎉 

## Self-hosted

I am assuming this will be the most common moving forward, since you can spin up a server and have it running. For that, you can import and use `translate` like:

```js
import translate from 'translate';   // (or require)

translate.engine = 'libre';
translate.url = 'https://mycustomurl.com/translate';
translate.key = '...';   // Optional, only if you have set up some key in your libretranslate server

(async () => {
  const text = await translate('Hello world', { from: 'en', to: 'es' });
})();
```

The `key` is only needed if you have [setup the server](https://github.com/uav4geo/LibreTranslate#arguments) with the argument `--api-keys`, otherwise you can ignore that line and it will work perfectly fine.

## Official website

If you are using the official website under the limit without a key, or you have received an official key, it's basically the same but omit the `url` since its already part of the module:


```js
import translate from 'translate';   // (or require)

translate.engine = 'libre';
translate.key = '...';   // Optional, only if you have received a key from the creator

(async () => {
  const text = await translate('Hello world', { from: 'en', to: 'es' });
})();
```

Hope that's clear!

**Comment by FranciscoMendes10866** [comment]
Amazing!

But now, when I add the url, the following error appears in the terminal:

```bash
FetchError: request to http://localhost:10866 failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/franciscomendes/Desktop/GIT/natice/ms-trans/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (node:events:378:20)
    at Socket.socketOnEnd (node:_http_client:486:9)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[ERROR] 16:00:05 FetchError: request to http://localhost:10866 failed, reason: socket hang up
```

**Comment by franciscop** [comment]
This seems like a backend issue, nothing that can be done on `translate` level. Please note that the docker image uses the default port `5000` and not `10866`. Does `http://localhost:10866/` work for you? As in, do you see translate homepage and can you make translations there?

**Comment by FranciscoMendes10866** [comment]
I mapped port 5000 to port 10866, I used the docker compose, when accessing `http://localhost:10866` I don't have it. However the docker container is running.

**Comment by franciscop** [comment]
You need to have the server running and accessible, if `http://localhost:10866` doesn't work then you need to fix that first. Unfortunately that's outside of `translate` and my ability, please follow up the instructions on https://github.com/uav4geo/LibreTranslate
