### ISSUE TITLE
Trouble with React

### ISSUE THREAD

**Issue by afuentes09651** [franciscop/translate#23]
Using the API as specified in the ReadMe produces an error with React unless I am not using it right

[App.js.txt](https://github.com/franciscop/translate/files/6144105/App.js.txt)

**Comment by afuentes09651** [comment]
Be advised that I uploaded the file in question as a txt to make it a supported file type for issues

**Comment by franciscop** [comment]
Can you reproduce in https://codesandbox.io/ please?

**Comment by franciscop** [comment]
It [seems to be working as intended](https://codesandbox.io/s/sharp-kowalevski-otnb5?file=/src/App.js)

**Comment by afuentes09651** [comment]
Hmm... interesting. I should be able to look at my project again tomorrow. Would you mind if I showed you more sometime this week?

**Comment by afuentes09651** [comment]
Bug has been fixed on my end. I appreciate your support as I am trying to practice React, and I really do not want to deal with writing any backend for my practice project. Thank you so much!

**Comment by afuentes09651** [comment]
I added credit to my ReadMe file on my project. I am getting used to GitHub so sorry it took a little while lol I usually just use it to push things and thats it
