### ISSUE TITLE
'Not a Function'

### ISSUE THREAD

**Issue by afuentes09651** [franciscop/translate#24]
I was wondering if the following error message is common for React:

×
Unhandled Rejection (TypeError): translate__WEBPACK_IMPORTED_MODULE_1___default() is not a function. (In 'translate__WEBPACK_IMPORTED_MODULE_1___default()(input, {
      to: langTo,
      from: langFrom
    })', 'translate__WEBPACK_IMPORTED_MODULE_1___default()' is an instance of Object)

found in [here](https://github.com/afuentes09651/translate/blob/master/src/components/Input.js)

**Comment by afuentes09651** [comment]
The error happens on a submit

**Comment by franciscop** [comment]
This is not a place to ask general React questions and I'm not your mentor.
