### ISSUE TITLE
DeepL support

### ISSUE THREAD

**Issue by Sly-Little-Fox** [franciscop/translate#31]
DeepL is often better than other translators.

**Comment by franciscop** [comment]
Great idea!

**Comment by franciscop** [comment]
@Sly-Little-Fox translate 1.3 has support for DeepL! You can use it like this:

```js
import translate from 'translate';

translate.engine = 'deepl';
translate.key = process.env.DEEPL_KEY;

const text = await translate('Hello world', 'es');
console.log(text);
```

**Comment by Sly-Little-Fox** [comment]
> @Sly-Little-Fox translate 1.3 has support for DeepL! You can use it like this:
> 
> ```js
> import translate from 'translate';
> 
> translate.engine = 'deepl';
> translate.key = process.env.DEEPL_KEY;
> 
> const text = await translate('Hello world', 'es');
> console.log(text);
> ```

Nice! Thanks.
