### ISSUE TITLE
Pontuation problem

### ISSUE THREAD

**Issue by kadu** [franciscop/translate#33]
I'm testing translate with this text:
 What do you call a pig that knows karate? A pork chop!

 And trying to translate to portuguese. 
I have getting only first part of text, until punctuation.

I'm using google as engine

**Comment by franciscop** [comment]
Thanks, fixed and added a test for it! Please upgrade to `translate@1.4.1` for using Google Translate with multi-sentences.

https://github.com/franciscop/translate/blob/master/src/engines/google.test.js#L51
