### ISSUE TITLE
yarn and npm issue

### ISSUE THREAD

**Issue by iM0hamed** [franciscop/translate#34]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2ftranslate - Not found
npm ERR! 404
npm ERR! 404  '@types/translate@^1.4.1' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by franciscop** [comment]
This library is `translate`, not `@types/translate`. Please install it with:

```
npm install translate
```

or

```
yarn add translate
```
