### ISSUE TITLE
Package still working ?

### ISSUE THREAD

**Issue by qlaffont** [franciscop/translate#40]
Hello,
I'm trying to use your package, but it seems it doesn't work. 
I have tried to use it, but didn't work. It returns the same input text.

Script Node.js (16.13.2)
```js
const translate = require('translate');

translate(" je m'appelle Quentin", { to: 'en', engine: 'google', key: 'YOUR KEY' }).then(
  (test) => console.log(test),
);
``` 

Same in browser context.

Thanks for your help
Regards.
Quentin LAFFONT

**Comment by qlaffont** [comment]
Found, need to precise from option

**Comment by franciscop** [comment]
Yes, if the original language is not English need to specify the language.
