### ISSUE TITLE
add typing

### ISSUE THREAD

**Issue by Mimexe** [franciscop/translate#44]
title, add typing to project with index.d.ts
Cause: `The declaration file of the module 'translate' is not found. d:/xx/xx/xxx/xx/node_modules/translate/translate.min.js' has implicitly a type 'any'.
  Try 'npm i --save-dev @types/translate' if it exists, or add a new declaration file (.d.ts) containing 'declare module "translate";'`
@types/translate dont exists

**Comment by euberdeveloper** [comment]
I already suggested this thing with this issue #19. Unfortunately he doesn't want to add the types.

**Comment by franciscop** [comment]
I didn't say that, I said that *I* am not going to add the types definition (nor move the project to typescript for that matter), but if someone contributes a high quality `index.d.ts` I'd accept it. It's still better to add it to `@types/translate` if possible though, so the community doesn't depend on me for types.

**Comment by franciscop** [comment]
Published `translate@2.0.0` with types! Note that if it's for Node.js, it does require Node 18+ or for you to polyfill fetch() (for the browser there's no change since fetch is available since forever).

**Comment by franciscop** [comment]
Feedback would be greatly appreciated since this is the first library I publish with types!
