### ISSUE TITLE
Issues with Node's 'require' implementation

### ISSUE THREAD

**Issue by bhawnishk** [franciscop/translate#48]
Hello @franciscop,

I'm trying to use this package for my node API but seems like it doesn't work with 'require'?

**Comment by franciscop** [comment]
Hi, Node has supported `import` for almost 6 years now so I decided to move this package to `import` recently. With that+Node supporting fetch() natively on Node 18 the installation and usage of this package should be easier and the same on browser and Node.

To use it with `require()` or older versions of Node, please install v1: `npm install translate@1`
