### ISSUE TITLE
Is this package supported with typescript?

### ISSUE THREAD

**Issue by muneeebsheikh** [franciscop/translate#50]
When I install translate package in my typescript project it doesn't let me start the project

```
const translate_1 = __importDefault(require("translate"));

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\me\misc\typescript\node_modules\translate\index.min.js from C:/myproject/index.js not supported.
Instead change the require of index.min.js in C:\me\misc\typescript\build\gateway.js to a dynamic import() which is available in all CommonJS modules.
```

the above error is occurred.

Please let me know if there's any thing I have to change or adjust to use this package. 
Thanks

**Comment by franciscop** [comment]
Hi, Node has supported `import` for almost 6 years now so I decided to move this package to `import` recently. With that+Node supporting fetch() natively on Node 18 the installation and usage of this package should be easier and the same on browser and Node.

To use it with `require()` or older versions of Node, please install v1: `npm install translate@1`
