### ISSUE TITLE
Handle Traditional Chinese (Not only simplified chinese)

### ISSUE THREAD

**Issue by Francoyy** [franciscop/translate#51]
Mandarin is a special language, as it has both traditional and simplified characters.
And the characters are not 1:1 mapping.
There may be N traditional characters that have only 1 simplified character equivalent.

This package only handles simplified chinese
https://github.com/franciscop/translate/blob/master/src/languages/iso.js#L30
https://github.com/franciscop/translate/blob/master/src/languages/names.js#L33

Google Translate offers both Simplified and Traditional chinese: https://cloud.google.com/translate/docs/languages
```
Chinese (Simplified)	zh-CN or zh ([BCP-47](https://tools.ietf.org/html/bcp47))
Chinese (Traditional)	zh-TW ([BCP-47](https://tools.ietf.org/html/bcp47))
```

Even though it seems that "zh-TW" is indeed not part of the ISO 639-1, it would be nice that it is still accepted as input language by this package, since Google Translate will accept this input language.
[Edit] As stated in [this document](https://cloud.google.com/translate/docs/languages), it seems they are indeed part of ISO 639-1, not sure why it's not on [this document](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

I manually changed the iso.js and names.js to add zh-TW as a personal workaround.

**Comment by franciscop** [comment]
Neither `zhtw` nor `zh-tw` are part of ISO 639, so please don't include them in that file. What you are referring to is to a local variation of a language, in the same way English UK and English US can be represented as `en-gb` and `en-us` respectively, `zh-tw` represents the Taiwan (ISO region `tw`) variant of Chinese (ISO language `zh`).

What we could add instead is support for regional variants by allowing local variations, something like this (note: a bit cleaner + add a test or two please):

```js
  // Make sure we have the correct name or throw
- if (!isoKeys.includes(name)) {
+ if (!isoKeys.includes(name) || /^[a-z]{2}-[a-z]{2}$/.test(name) && !isoKeys.includes(name.slice(0, 2))) {
    throw new Error(`The language "${name.slice(0, 2)}" is not part of the ISO 639-1`);
  }
```

**Comment by Francoyy** [comment]
zh-tw is not just a "regional variant" of zh. To put it simple, "zh" = Simplified Chinese with simplified Characters. "zh-tw" or "zh-hk" = Traditional Chinese with traditional characters. They are a completely different set of characters, and they are not a 1:1 mapping and it is not recommended to use scripts to map one with the other.
More info here https://en.wikipedia.org/wiki/Ambiguities_in_Chinese_character_simplification

By not accepting zh-tw, you're blocking more than 30 million people from using your tool.
As I see it, the correct implementation should simply accept whatever the translation engines accept, a whitelist of the current languages accepted.

I'll see if I can make another PR with your solution, but I don't have time in the near future. I'll just use my local changes to use Google Translate with zh-tw.

**Comment by franciscop** [comment]
> I'll just use my local changes to use Google Translate with zh-tw.

That definitely works

> You're blocking more than 30 million people from using your tool.

That language is not okay ☹️
