### ISSUE TITLE
Detect language

### ISSUE THREAD

**Issue by mybearworld** [franciscop/translate#53]
Currently, this module requires you to specify a language. A detect language feature would help here.

**Comment by franciscop** [comment]
There's a dozen different way we could go around detecting languages and so 5million google results for it; this library called `translate` is exclusively for translating text. But it's built in a way it's easy to compose, so once you find the way you want to do language detection it's very easy to integrate in your code:

```js
import translate from 'translate';
import detect from 'wherever-you-want';

// Combine both of them into a single function
const myTranslate = (str, to) => detect(str).then(from => translate(str, { from, to }));

// Use it as you please:
await myTranslate('こんにちは、世界', 'en');
// Hello, world
```

<img width="891" alt="image" src="https://github.com/franciscop/translate/assets/2801252/02ee4b8b-736d-449e-a689-17ed44130648">
