### ISSUE TITLE
[Feature Request] - There should be a method to detect a language of a given string.

### ISSUE THREAD

**Issue by Noushad-web** [franciscop/translate#55]
I encountered a situation in which I have a string that may contain different languages. Therefore, before converting it to a specific language, I need to detect its language.
Instead of relying on another package or translation API for detection, this package should include a function to detect the language of a given string.

we can use google translation [api](https://cloud.google.com/translate/docs/basic/detecting-language#translate_detect_language-nodejs) or something else.

**Comment by franciscop** [comment]
https://github.com/franciscop/translate/issues/53
