### ISSUE TITLE
How to get more than one possible meaning ?

### ISSUE THREAD

**Issue by karanrajput1999** [franciscop/translate#56]
Is there a way to get more than one possible meaning ? like - I am translating from english to hindi, let's say I am translating the word "ram" it has more than one meaning how do I get those ?

**Comment by franciscop** [comment]
Unfortunately it's not possible with translate and IMHO it'd change too drastically the API. I'm also not even sure it's supported across the board. The way to work around those usually is to add context: "A ram is a type of sheep" vs "We ram the car into the garage door" (though I understand that's not valid for many applications).
