### ISSUE TITLE
Google Translate v2 key not working

### ISSUE THREAD

**Issue by germanviscuso** [franciscop/translate#6]
How am I supposed to pass the key to translate? Google Translate gave me a json file with several entries as key and if I try to pass the value for the one named "private_key" it doesn't work (says invalid key). If I have to pass a path to this json file that will be problematic for my project

**Comment by franciscop** [comment]
Could you please show me the code that you are using? (*HIDE THE KEYS*). It should not be a private key that you are using, but the API key that you can find in https://console.developers.google.com/apis/credentials . See example:

![google api key](https://user-images.githubusercontent.com/2801252/47494337-61a4a000-d88c-11e8-83c5-7b213062c8bb.png)

**Comment by franciscop** [comment]
Please let me know if this fixes the issue.

**Comment by franciscop** [comment]
Seems like the OP was trying to use the wrong key and there are no updates on their side, so I'm closing this as invalid.

**Comment by germanviscuso** [comment]
I confirm it worked as you've shown. Sorry for the invalid issue!
