### ISSUE TITLE
Google Cloud seems to have changed their auth API

### ISSUE THREAD

**Issue by Tresky** [franciscop/translate#9]
As this library currently exists, I can't get the Google engine to function properly. I looked into the issue a bit and noticed that this is the URL this library is currently using to send requests to:
```
https://translation.googleapis.com/language/translate/v2?key=${key}&source=${from}&target=${to}&q=${query}
```

The `key` param seems to be deprecated. It doesn't seem to work unless I change it to `access_token`. So, this library should be updated to use `access_token` instead of `key`.

In addition to this change, GCloud no longer distributes just API keys. The API key mentioned in #6 no longer seems to function. GCloud now distributes their new auth packet in the form of a JSON file you get offered when you create your project in their admin panel. To get the new `access_token` you can run the following command.

`GOOGLE_APPLICATION_CREDENTIALS=creds.json gcloud auth application-default print-access-token` where `creds.json` is the JSON packet that GCloud has you download.

**Comment by franciscop** [comment]
Could you please provide the docs where it says that the key is deprecated? My google free trial run out so I cannot test it, but the credentials page does not say anything about it being deprecated. Can you check also whether creating an API key here works for you?

https://console.developers.google.com/apis/credentials

**Comment by franciscop** [comment]
The documentation does not seem to say anything about it being deprecated:

https://cloud.google.com/translate/docs/reference/translate

It _does_ say that OAuth 2.0 is preferred, but not that the API key is deprecated.

**Comment by Tresky** [comment]
I saw also in the docs that it doesn't necessarily say *deprecated*, but it also doesn't seem to work, so I'm not entirely sure what is going on with it.

**Comment by franciscop** [comment]
That's a different issue. Seems like you read #6, which step failed?

- Could you get the API key from Google?
- Did you give that key permission for Google Translate?
- Did the HTTP request complete successfully?
- Did any error get thrown in the console meanwhile?

With this info I might be able to help
